######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 4 14:09:49 2013
######################################################################

TEMPLATE = app
TARGET = termocoppia
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += serial.hpp tc.hpp
FORMS += termocoppia.ui
SOURCES += main.cpp serial.cpp tc.cpp
